from mininet.topo import Topo
from mininet.cli import CLI
from mininet.log import lg
from mininet.node import Node
from mininet.topolib import TreeNet
from mininet.node import RemoteController, OVSKernelSwitch
from mininet.net import Mininet


def startNAT( root, inetIntf='eth0', subnet='10.0/8' ):
    """Start NAT/forwarding between Mininet and external network
    root: node to access iptables from
    inetIntf: interface for internet access
    subnet: Mininet subnet (default 10.0/8)="""

    # Identify the interface connecting to the mininet network
    localIntf = root.defaultIntf()

    # Flush any currently active rules
    root.cmd( 'iptables -F' )
    root.cmd( 'iptables -t nat -F' )

    # Create default entries for unmatched traffic
    root.cmd( 'iptables -P INPUT ACCEPT' )
    root.cmd( 'iptables -P OUTPUT ACCEPT' )
    root.cmd( 'iptables -P FORWARD DROP' )

    # Configure NAT
    root.cmd( 'iptables -I FORWARD -i', localIntf, '-d', subnet, '-j DROP' )
    root.cmd( 'iptables -A FORWARD -i', localIntf, '-s', subnet, '-j ACCEPT' )
    root.cmd( 'iptables -A FORWARD -i', inetIntf, '-d', subnet, '-j ACCEPT' )
    root.cmd( 'iptables -t nat -A POSTROUTING -o ', inetIntf, '-j MASQUERADE' )

    # Instruct the kernel to perform forwarding
    root.cmd( 'sysctl net.ipv4.ip_forward=1' )

def stopNAT( root ):
    """Stop NAT/forwarding between Mininet and external network"""
    # Flush any currently active rules
    root.cmd( 'iptables -F' )
    root.cmd( 'iptables -t nat -F' )

    # Instruct the kernel to stop forwarding
    root.cmd( 'sysctl net.ipv4.ip_forward=0' )

def fixNetworkManager( root, intf ):
    """Prevent network-manager from messing with our interface,
       by specifying manual configuration in /etc/network/interfaces
       root: a node in the root namespace (for running commands)
       intf: interface name"""
    cfile = '/etc/network/interfaces'
    line = '\niface %s inet manual\n' % intf
    config = open( cfile ).read()
    if line not in config:
        print '*** Adding', line.strip(), 'to', cfile
        with open( cfile, 'a' ) as f:
            f.write( line )
        # Probably need to restart network-manager to be safe -
        # hopefully this won't disconnect you
        root.cmd( 'service network-manager restart' )

def connectToInternet( network, switch='s1', rootip='10.254', subnet='10.0/8'):
    """Connect the network to the internet
       switch: switch to connect to root namespace
       rootip: address for interface in root namespace
       subnet: Mininet subnet"""
    switch = network.get( switch )
    prefixLen = subnet.split( '/' )[ 1 ]

    # Create a node in root namespace
    root = Node( 'root', inNamespace=False )

    # Prevent network-manager from interfering with our interface
    fixNetworkManager( root, 'root-eth0' )

    # Create link between root NS and switch
    link = network.addLink( root, switch )
    link.intf1.setIP( rootip, prefixLen )

    # Start network that now includes link to root namespace
    network.start()

    # Start NAT and establish forwarding
    startNAT( root )

    # Establish routes from end hosts
    for host in network.hosts:
        host.cmd( 'ip route flush root 0/0' )
        host.cmd( 'route add -net', subnet, 'dev', host.defaultIntf() )
        host.cmd( 'route add default gw', rootip )

    return root



if __name__ == "__main__":
    lg.setLogLevel( 'info')
    #net = TreeNet( depth=1, fanout=4 )
    # Configure and start NATted connectivity
    net = Mininet(listenPort = 6633)

    mycontroller = RemoteController("C0",ip = "192.168.176.132")
    net.addController(mycontroller)

    # Add hosts and switches
    Switch01 = net.addSwitch('s1')
    Switch02 = net.addSwitch('s2')
    Switch03 = net.addSwitch('s3')
    Switch04 = net.addSwitch('s4')
    Switch05 = net.addSwitch('s5')
    Switch06 = net.addSwitch('s6')
    Switch07 = net.addSwitch('s7')
    Switch08 = net.addSwitch('s8')
    Switch09 = net.addSwitch('s9')
    Switch10 = net.addSwitch('s10')
    Switch11 = net.addSwitch('s11')
    Switch12 = net.addSwitch('s12')
    Switch13 = net.addSwitch('s13')
    Switch14 = net.addSwitch('s14')
    Switch15 = net.addSwitch('s15')
    Switch16 = net.addSwitch('s16')
    Switch17 = net.addSwitch('s17')
    Switch18 = net.addSwitch('s18')
    Switch19 = net.addSwitch('s19')
    Switch20 = net.addSwitch('s20')
    Switch21 = net.addSwitch('s21')
    Switch22 = net.addSwitch('s22')
    Switch23 = net.addSwitch('s23')
    Switch24 = net.addSwitch('s24')
    Switch25 = net.addSwitch('s25')
    Switch26 = net.addSwitch('s26')
    Switch27 = net.addSwitch('s27')
    Switch28 = net.addSwitch('s28')
    Switch29 = net.addSwitch('s29')
    Switch30 = net.addSwitch('s30')
    Switch31 = net.addSwitch('s31')
    Switch32 = net.addSwitch('s32')
    Switch33 = net.addSwitch('s33')
    Switch34 = net.addSwitch('s34')
    Switch35 = net.addSwitch('s35')
    Switch36 = net.addSwitch('s36')
    Switch37 = net.addSwitch('s37')
    Switch38 = net.addSwitch('s38')
    Switch39 = net.addSwitch('s39')
    Switch40 = net.addSwitch('s40')
    Switch41 = net.addSwitch('s41')

    Host01 = net.addHost('h1')
    Host02 = net.addHost('h2')
    Host03 = net.addHost('h3')
    Host04 = net.addHost('h4')
    Host05 = net.addHost('h5')
    Host06 = net.addHost('h6')
    Host07 = net.addHost('h7')
    Host08 = net.addHost('h8')
    Host09 = net.addHost('h9')
    Host10 = net.addHost('h10')
    Host11 = net.addHost('h11')
    Host12 = net.addHost('h12')
    Host13 = net.addHost('h13')
    Host14 = net.addHost('h14')
    Host15 = net.addHost('h15')
    Host16 = net.addHost('h16')
    Host17 = net.addHost('h17')
    Host18 = net.addHost('h18')
    Host19 = net.addHost('h19')
    Host20 = net.addHost('h20')
    Host21 = net.addHost('h21')
    Host22 = net.addHost('h22')
    Host23 = net.addHost('h23')
    Host24 = net.addHost('h24')
    Host25 = net.addHost('h25')
    Host26 = net.addHost('h26')
    Host27 = net.addHost('h27')
    Host28 = net.addHost('h28')
    Host29 = net.addHost('h29')
    Host30 = net.addHost('h30')
    Host31 = net.addHost('h31')
    Host32 = net.addHost('h32')
    Host33 = net.addHost('h33')
    Host34 = net.addHost('h34')
    Host35 = net.addHost('h35')
    Host36 = net.addHost('h36')
    Host37 = net.addHost('h37')
    Host38 = net.addHost('h38')
    Host39 = net.addHost('h39')
    Host40 = net.addHost('h40')
    Host41 = net.addHost('h41')
    Host42 = net.addHost('h42')
    Host43 = net.addHost('h43')
    Host44 = net.addHost('h44')
    Host45 = net.addHost('h45')
    Host46 = net.addHost('h46')
    Host47 = net.addHost('h47')
    Host48 = net.addHost('h48')
    Host49 = net.addHost('h49')
    Host50 = net.addHost('h50')
    Host51 = net.addHost('h51')
    Host52 = net.addHost('h52')
    Host53 = net.addHost('h53')
    Host54 = net.addHost('h54')
    Host55 = net.addHost('h55')
    Host56 = net.addHost('h56')
    Host57 = net.addHost('h57')
    Host58 = net.addHost('h58')
    Host59 = net.addHost('h59')
    Host60 = net.addHost('h60')
    Host61 = net.addHost('h61')
    Host62 = net.addHost('h62')
    Host63 = net.addHost('h63')
    Host64 = net.addHost('h64')
    Host65 = net.addHost('h65')
    Host66 = net.addHost('h66')
    Host67 = net.addHost('h67')
    Host68 = net.addHost('h68')
    Host69 = net.addHost('h69')
    Host70 = net.addHost('h70')
    Host71 = net.addHost('h71')
    Host72 = net.addHost('h72')
    Host73 = net.addHost('h73')
    Host74 = net.addHost('h74')
    Host75 = net.addHost('h75')
    Host76 = net.addHost('h76')
    Host77 = net.addHost('h77')
    Host78 = net.addHost('h78')
    Host79 = net.addHost('h79')
    Host80 = net.addHost('h80')
    Host81 = net.addHost('h81')
    Host82 = net.addHost('h82')
    Host83 = net.addHost('h83')
    Host84 = net.addHost('h84')
    Host85 = net.addHost('h85')
    Host86 = net.addHost('h86')
    Host87 = net.addHost('h87')
    Host88 = net.addHost('h88')
    Host89 = net.addHost('h89')
    Host90 = net.addHost('h90')
    Host91 = net.addHost('h91')
    Host92 = net.addHost('h92')
    Host93 = net.addHost('h93')
    Host94 = net.addHost('h94')
    Host95 = net.addHost('h95')
    Host96 = net.addHost('h96')
    Host97 = net.addHost('h97')
    Host98 = net.addHost('h98')
    Host99 = net.addHost('h99')
    Host100 = net.addHost('h100')
    Host101 = net.addHost('h101')
    Host102 = net.addHost('h102')
    Host103 = net.addHost('h103')
    Host104 = net.addHost('h104')
    Host105 = net.addHost('h105')
    Host106 = net.addHost('h106')
    Host107 = net.addHost('h107')
    Host108 = net.addHost('h108')
    Host109 = net.addHost('h109')
    Host110 = net.addHost('h110')
    Host111 = net.addHost('h111')
    Host112 = net.addHost('h112')
    Host113 = net.addHost('h113')
    Host114 = net.addHost('h114')
    Host115 = net.addHost('h115')
    Host116 = net.addHost('h116')
    Host117 = net.addHost('h117')
    Host118 = net.addHost('h118')
    

    # Add links
    net.addLink(Switch01,Switch02)
    net.addLink(Switch01,Switch03)
    net.addLink(Switch01,Switch04)
    net.addLink(Switch02,Switch05)
    net.addLink(Switch02,Switch07)
    net.addLink(Switch02,Switch13)
    net.addLink(Switch03,Switch04)
    net.addLink(Switch03,Switch07)
    net.addLink(Switch03,Switch08)
    net.addLink(Switch03,Switch09)
    net.addLink(Switch04,Switch05)
    net.addLink(Switch04,Switch10)
    net.addLink(Switch04,Switch11)
    net.addLink(Switch05,Switch12)
    net.addLink(Switch05,Switch13)
    net.addLink(Switch06,Switch07)
    net.addLink(Switch06,Switch13)
    net.addLink(Switch06,Switch14)
    net.addLink(Switch06,Switch16)
    net.addLink(Switch06,Switch17)
    net.addLink(Switch07,Switch08)
    net.addLink(Switch07,Switch20)
    net.addLink(Switch07,Switch21)
    net.addLink(Switch07,Switch22)
    net.addLink(Switch08,Switch22)
    net.addLink(Switch08,Switch23)
    net.addLink(Switch09,Switch10)
    net.addLink(Switch09,Switch26)
    net.addLink(Switch10,Switch29)
    net.addLink(Switch10,Switch30)
    net.addLink(Switch10,Switch33)
    net.addLink(Switch11,Switch12)
    net.addLink(Switch11,Switch34)
    net.addLink(Switch11,Switch35)
    net.addLink(Switch12,Switch36)
    net.addLink(Switch12,Switch37)
    net.addLink(Switch13,Switch39)
    net.addLink(Switch14,Switch15)
    net.addLink(Switch14,Switch16)
    net.addLink(Switch15,Switch16)
    net.addLink(Switch16,Switch18)
    net.addLink(Switch17,Switch18)
    net.addLink(Switch17,Switch19)
    net.addLink(Switch20,Switch21)
    net.addLink(Switch23,Switch24)
    net.addLink(Switch23,Switch25)
    net.addLink(Switch26,Switch27)
    net.addLink(Switch26,Switch28)
    net.addLink(Switch27,Switch28)
    net.addLink(Switch30,Switch31)
    net.addLink(Switch30,Switch32)
    net.addLink(Switch35,Switch36)
    net.addLink(Switch36,Switch38)
    net.addLink(Switch37,Switch38)
    net.addLink(Switch39,Switch40)
    net.addLink(Switch39,Switch41)
    net.addLink(Switch15,Host01)
    net.addLink(Switch15,Host02)
    net.addLink(Switch18,Host03)
    net.addLink(Switch18,Host04)
    net.addLink(Switch18,Host05)
    net.addLink(Switch19,Host06)
    net.addLink(Switch19,Host07)
    net.addLink(Switch20,Host08)
    net.addLink(Switch20,Host09)
    net.addLink(Switch20,Host10)
    net.addLink(Switch21,Host11)
    net.addLink(Switch21,Host12)
    net.addLink(Switch21,Host13)
    net.addLink(Switch21,Host14)
    net.addLink(Switch21,Host15)
    net.addLink(Switch22,Host16)
    net.addLink(Switch22,Host17)
    net.addLink(Switch24,Host18)
    net.addLink(Switch24,Host19)
    net.addLink(Switch24,Host20)
    net.addLink(Switch24,Host21)
    net.addLink(Switch24,Host22)
    net.addLink(Switch24,Host23)
    net.addLink(Switch24,Host24)
    net.addLink(Switch24,Host25)
    net.addLink(Switch24,Host26)
    net.addLink(Switch24,Host27)
    net.addLink(Switch25,Host28)
    net.addLink(Switch25,Host29)
    net.addLink(Switch25,Host30)
    net.addLink(Switch25,Host31)
    net.addLink(Switch25,Host32)
    net.addLink(Switch25,Host33)
    net.addLink(Switch25,Host34)
    net.addLink(Switch25,Host35)
    net.addLink(Switch25,Host36)
    net.addLink(Switch25,Host37)
    net.addLink(Switch28,Host38)
    net.addLink(Switch28,Host39)
    net.addLink(Switch28,Host40)
    net.addLink(Switch28,Host41)
    net.addLink(Switch28,Host42)
    net.addLink(Switch28,Host43)
    net.addLink(Switch28,Host44)
    net.addLink(Switch29,Host45)
    net.addLink(Switch29,Host46)
    net.addLink(Switch29,Host47)
    net.addLink(Switch29,Host48)
    net.addLink(Switch29,Host49)
    net.addLink(Switch31,Host50)
    net.addLink(Switch31,Host51)
    net.addLink(Switch31,Host52)
    net.addLink(Switch31,Host53)
    net.addLink(Switch31,Host54)
    net.addLink(Switch31,Host55)
    net.addLink(Switch31,Host56)
    net.addLink(Switch31,Host57)
    net.addLink(Switch31,Host58)
    net.addLink(Switch31,Host59)
    net.addLink(Switch31,Host60)
    net.addLink(Switch31,Host61)
    net.addLink(Switch32,Host62)
    net.addLink(Switch32,Host63)
    net.addLink(Switch32,Host64)
    net.addLink(Switch32,Host65)
    net.addLink(Switch32,Host66)
    net.addLink(Switch32,Host67)
    net.addLink(Switch32,Host68)
    net.addLink(Switch32,Host69)
    net.addLink(Switch32,Host70)
    net.addLink(Switch32,Host71)
    net.addLink(Switch33,Host72)
    net.addLink(Switch33,Host73)
    net.addLink(Switch33,Host74)
    net.addLink(Switch33,Host75)
    net.addLink(Switch33,Host76)
    net.addLink(Switch33,Host77)
    net.addLink(Switch34,Host78)
    net.addLink(Switch34,Host79)
    net.addLink(Switch34,Host80)
    net.addLink(Switch35,Host81)
    net.addLink(Switch35,Host82)
    net.addLink(Switch36,Host83)
    net.addLink(Switch36,Host84)
    net.addLink(Switch36,Host85)
    net.addLink(Switch36,Host86)
    net.addLink(Switch38,Host87)
    net.addLink(Switch38,Host88)
    net.addLink(Switch38,Host89)
    net.addLink(Switch38,Host90)
    net.addLink(Switch38,Host91)
    net.addLink(Switch37,Host92)
    net.addLink(Switch37,Host93)
    net.addLink(Switch37,Host94)
    net.addLink(Switch37,Host95)
    net.addLink(Switch41,Host96)
    net.addLink(Switch41,Host97)
    net.addLink(Switch41,Host98)
    net.addLink(Switch41,Host99)
    net.addLink(Switch41,Host100)
    net.addLink(Switch41,Host101)
    net.addLink(Switch41,Host102)
    net.addLink(Switch41,Host103)
    net.addLink(Switch41,Host104)
    net.addLink(Switch41,Host105)
    net.addLink(Switch41,Host106)
    net.addLink(Switch40,Host107)
    net.addLink(Switch40,Host108)
    net.addLink(Switch40,Host109)
    net.addLink(Switch40,Host110)
    net.addLink(Switch40,Host111)
    net.addLink(Switch40,Host112)
    net.addLink(Switch40,Host113)
    net.addLink(Switch40,Host114)
    net.addLink(Switch40,Host115)
    net.addLink(Switch40,Host116)
    net.addLink(Switch40,Host117)
    net.addLink(Switch40,Host118)
        

    rootnode = connectToInternet( net )
    print "*** Hosts are running and should have internet connectivity"
    print "*** Type 'exit' or control-D to shut down network"
    CLI( net )
    stopNAT( rootnode )
    net.stop()
